### ISSUE TITLE
Weird errors and warning messages

### ISSUE THREAD

**Issue by caraya** [SassDoc/grunt-sassdoc#12]
I'm using grunt-sassdoc to generate docs from multiple directories. The errors I'm getting are these:
 
Running "sassdoc:all" (sassdoc) task
/Users/carlos/code/typography-sass/columns/columns.scss:NaN [ ] --force
/Users/carlos/code/typography-sass/fonts/fonts.scss:NaN [ ] --force
/Users/carlos/code/typography-sass/maps/sm-colors.scss:NaN [ ] --force
/Users/carlos/code/typography-sass/maps/maps-typography.scss:NaN [ ] --force
/Users/carlos/code/typography-sass/media-queries/hdpi-mq.scss:NaN [ ] --force
/Users/carlos/code/typography-sass/media-queries/iphone-ipad-mq-examples.scss:NaN [ ] --force
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
Warning: Exited with error code 64 Used --force, continuing.
» [WARNING] Parser for annotation `flag` not found. Location: `linePoster.test.scss:5:8`
>> SassDoc documentation successfully generated.

This is what I'm using to generate the docs:
      sassdoc: {
        all: {
          src: '**/*.scss',
          options: {
            dest: 'sassdocs',
            display: {
              access: ['public', 'private']
            }
          }
        }
      },

and my system config:
Node 0.12.0
grunt-sassdoc 2.1.15
grunt-cli v0.1.13
grunt v0.4.5

Is there something I need to change to remove the errors?

**Comment by pascalduez** [comment]
Hi,

is your stack/code visible online by ony chance ?

The `src` pattern looks odd, try something like `.scss` or `**/*.scss` if you have nested dirs.

**Comment by caraya** [comment]
I had it set up as **/*.scss

I fixed the issue by changing the sassdoc task to:

sassdoc: {
        all: {
          src: [
           '**/*.scss',
            '!/node_modules'
          ],
          options: {
            dest: 'sassdocs',
            display: {
              access: ['public', 'private']
            }
          }
        }

Still can't figure out what cause the weirdness but it looks like it's fixed when nI run the grunt file manually and through Travis

Sorry about the noise.

**Comment by pascalduez** [comment]
I would recommend to target a source folder more precisely, so it doesn't have to scan the whole folder while looking for SCSS files. And so you don't need the negation pattern. Something like `./sass/**/*.scss`
