### ISSUE TITLE
Get these two warning when I installed it today 

### ISSUE THREAD

**Issue by jitendravyas** [SassDoc/grunt-sassdoc#18]
npm WARN deprecated swig@1.4.0: This package is no longer maintained
npm WARN prefer global marked@0.3.6 should be installed with -g

**Comment by pascalduez** [comment]
Hi,

not related to grunt-sassdoc but sassdoc itself.
Not much we can do about it actually, but they are "just" warnings.

For the default theme rewrite: SassDoc/sassdoc-theme-default#96
There's also an issue on the marked project to remove this warning.
