### ISSUE TITLE
>> Error: Cannot find module 'postcss-scss'

### ISSUE THREAD

**Issue by jitendravyas** [SassDoc/grunt-sassdoc#19]
Gets this error when I run 

```
❯ grunt sassdoc
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'postcss-scss'
```

**Comment by pascalduez** [comment]
Hi,

we would need a bit more informations, that's not a proper issue report.

We don't have this dependency in any of SassDoc's packages, so I would rather look at your Grunffile or other dependencies.
