### ISSUE TITLE
Add support for `--sass-convert` option

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/grunt-sassdoc#2]
Upcoming in SassDoc `1.7.0`

**Comment by bjudson** [comment]
Can I ask why you set this to wontfix? Would be really useful for our team...

**Comment by pascalduez** [comment]
I thought I targeted this at version `2.0` of the plugin actually.

Anyway, SassDoc `2.0` is in RC and currently in testing phase. `.sass` to `.scss` conversion is intrinsic now so you don't even have to set an option.

So I would advise you to start using `2.0` now. The Grunt plugin is ready as well. 
Just `npm i grunt-sassdoc@beta -D` 

If for some reasons you really need to stick to `1.0` I will implement it.

**Comment by bjudson** [comment]
We'll upgrade to `2.0` and try it out. Thanks!
