### ISSUE TITLE
force vs no-prompt

### ISSUE THREAD

**Issue by allanhortle** [SassDoc/grunt-sassdoc#7]
There is a bit of a discrepancy between the cli and the grunt task so it took me a while to figure out how to disable override prompts. This should either use similar language or documented somewhere.

**Comment by jsit** [comment]
I don't see any of this documented on the sassdoc site anymore.

https://www.google.com/search?q=site%3Asassdoc.com+%22force%22

**Comment by pascalduez** [comment]
Hi @jsit,

starting from SassDoc 2.0 there no `force` option anymore.

>  --no-prompt option no longer exists since SassDoc outputs its own folder (#302)

See https://github.com/SassDoc/sassdoc/blob/master/CHANGELOG.md#api-breaks-for-users
See https://github.com/SassDoc/sassdoc/issues/302

So `grunt-sassdoc` >=2.0 is following SassDoc core behavior. Meaning there's only a `src` key necessary as in the [examples](http://sassdoc.com/grunt/#examples). The docs files will be output in a `sassdoc` folder and that folder wiped without prompt. 
If for some reasons you want to cutomise the output folder, you can do in with the `dest` **option**, either directly in the grunt task, or in a `.sassdocrc` if you have one.

**Comment by jsit** [comment]
@pascalduez, that's not the whole story -- I do still need to put `force: true` in my Gruntfile options if I'm specifying a `dest`. sassdoc 2.1.11

**Comment by pascalduez** [comment]
> I do still need to put force: true in my Gruntfile options if I'm specifying a dest.

Yes, that's the intended behaviour. We consider the default `sassdoc` folder safe to wipe without notice, but still prefer to have a security check for user provided ones.

Maybe the Grunt plugin could set `force` to `true` if the `dest` option is specified.
But I'd prefer to keep the plugin as close as possible to the core.
